/*
 * EXAMPLE_2.C
 *
 * This program checks the accuracy of the timer interrupt tick.
 *
 * The program prints the real-time clock time, then waits 1000 ticks and prints again.
 * Printing should be at exactly 10 seconds intervals. The timer tick, at 10 ms intervals
 * (100 interrupts per second) is generated by an internal timer in the Windows operating
 * system.
 *
 */

#include <ucos_ii.h>
#include <stdio.h>
#include <time.h>

#define STACKSIZE  256

/* Stack */
OS_STK TaskStk[STACKSIZE];

/* Prototypes */
void Task(void *);

void main(void)
{
    OSInit();
    OSTaskCreate(Task, OS_NULL, &TaskStk[STACKSIZE], 10);
    OSStart();
}

void Task(void *pdata)
{
    time_t t;

    for (;;) {
        t = time(NULL);
        printf("%s", ctime(&t));
        OSTimeDly(1000);
    }
}
